backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads
site_url: https://hope-in-us.netlify.app/
editor:
  preview: false

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  - name: homepages
    label: Hompages
    files:
      - file: "data/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Titre
            name: title
            widget: markdown
          - label: Contexte
            name: context
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Contenu, name: content, widget: markdown}
          - label: Objectifs
            name: objectif
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - {label: Contenu, name: content, widget: markdown}
              - {label: Groupe-Intro, name: group_intro, widget: string}
              - {label: Item 1, name: group_item_1, widget: string}
              - {label: Item 2, name: group_item_2, widget: string}
              - {label: Item 3, name: group_item_3, widget: string}
          - label: Etapes
            name: steps
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - {label: Item HIU, name: hiu, widget: markdown}
              - {label: Item WebTV, name: webtv, widget: markdown}
              - {label: Item Outils, name: tools, widget: markdown}
          - label: Contact
            name: contact
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
          - label: Footer
            name: footer
            widget: object
            fields:
              - {label: Copyright, name: copyright, widget: string}
              - {label: Erasmus, name: erasmus, widget: markdown}
      - file: "data/homeen.yml"
        label: Homepage EN
        name: home-en
        fields:
          - label: Titre
            name: title
            widget: markdown
          - label: Contexte
            name: context
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Contenu, name: content, widget: markdown}
          - label: Objectifs
            name: objectif
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - {label: Contenu, name: content, widget: markdown}
              - {label: Groupe-Intro, name: group_intro, widget: string}
              - {label: Item 1, name: group_item_1, widget: string}
              - {label: Item 2, name: group_item_2, widget: string}
              - {label: Item 3, name: group_item_3, widget: string}
          - label: Etapes
            name: steps
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - {label: Item HIU, name: hiu, widget: markdown}
              - {label: Item WebTV, name: webtv, widget: markdown}
              - {label: Item Outils, name: tools, widget: markdown}
          - label: Contact
            name: contact
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
          - label: Footer
            name: footer
            widget: object
            fields:
              - {label: Copyright, name: copyright, widget: string}
              - {label: Erasmus, name: erasmus, widget: markdown}
      - file: "data/homees.yml"
        label: Homepage ES
        name: home-es
        fields:
          - label: Titre
            name: title
            widget: markdown
          - label: Contexte
            name: context
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Contenu, name: content, widget: markdown}
          - label: Objectifs
            name: objectif
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - {label: Contenu, name: content, widget: markdown}
              - {label: Groupe-Intro, name: group_intro, widget: string}
              - {label: Item 1, name: group_item_1, widget: string}
              - {label: Item 2, name: group_item_2, widget: string}
              - {label: Item 3, name: group_item_3, widget: string}
          - label: Etapes
            name: steps
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - {label: Item HIU, name: hiu, widget: markdown}
              - {label: Item WebTV, name: webtv, widget: markdown}
              - {label: Item Outils, name: tools, widget: markdown}
          - label: Contact
            name: contact
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
          - label: Footer
            name: footer
            widget: object
            fields:
              - {label: Copyright, name: copyright, widget: string}
              - {label: Erasmus, name: erasmus, widget: markdown}
  - name: pages
    label: Pages
    files:
      - file: "data/pages/fr.yml"
        label: "Pages Fr"
        name: fr
        fields:
          - label: "Communauté"
            name: community
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: content, widget: markdown}
                  - {label: Link, name: link, widget: string}
          - label: "Boite à outils"
            name: tools
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Documents
                name: files
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Contenu, name: content, widget: markdown}
                  - {label: PDF, name: file, widget: file}
                  - {label: Video Youtube, name: linkvideo, widget: string}
                  - {label: Texte Vidéo, name: textvideo, widget: markdown}
          - label: "Web TV"
            name: webtv
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Liens
                name: lonks
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: URL Youtube, name: link, widget: string}
                  - {label: Label, name: label, widget: string, default: "Lire la vidéo"}
      - file: "data/pages/en.yml"
        label: "Pages En"
        name: en
        fields:
          - label: "Communauté"
            name: community
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: content, widget: markdown}
                  - {label: Link, name: link, widget: string}
          - label: "Boite à outils"
            name: tools
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Documents
                name: files
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Contenu, name: content, widget: markdown}
                  - {label: PDF, name: file, widget: file}
                  - {label: Video Youtube, name: linkvideo, widget: string}
                  - {label: Texte Vidéo, name: textvideo, widget: markdown}
          - label: "Web TV"
            name: webtv
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Liens
                name: lonks
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: URL Youtube, name: link, widget: string}
                  - {label: Label, name: label, widget: string, default: "Lire la vidéo"}
      - file: "data/pages/es.yml"
        label: "Pages ES"
        name: es
        fields:
          - label: "Communauté"
            name: community
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Content, name: content, widget: markdown}
                  - {label: Link, name: link, widget: string}
          - label: "Boite à outils"
            name: tools
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Documents
                name: files
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Contenu, name: content, widget: markdown}
                  - {label: PDF, name: file, widget: file}
                  - {label: Video Youtube, name: linkvideo, widget: string}
                  - {label: Texte Vidéo, name: textvideo, widget: markdown}
          - label: "Web TV"
            name: webtv
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: markdown}
              - label: Liens
                name: lonks
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: URL Youtube, name: link, widget: string}
                  - {label: Label, name: label, widget: string, default: "Lire la vidéo"}
  - name: bao
    label: "Boite à outils"
    files:
      - file: "data/bao/bao-fr.yml"
        label: "BAO en français"
        name: bao-fr
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Documents
            name: files
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Contenu, name: content, widget: markdown}
              - {label: PDF, name: file, widget: file}
              - {label: Video Youtube, name: linkvideo, widget: string}
              - {label: Texte Vidéo, name: textvideo, widget: markdown}
      - file: "data/bao/bao-en.yml"
        label: "BAO en anglais"
        name: bao-en
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Documents
            name: files
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Contenu, name: content, widget: markdown}
              - {label: PDF, name: file, widget: file}
              - {label: Video Youtube, name: linkvideo, widget: string}
              - {label: Texte Vidéo, name: textvideo, widget: markdown}
      - file: "data/bao/bao-es.yml"
        label: "BAO en espagnol"
        name: bao-es
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Documents
            name: files
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Contenu, name: content, widget: markdown}
              - {label: PDF, name: file, widget: file}
              - {label: Video Youtube, name: linkvideo, widget: string}
              - {label: Texte Vidéo, name: textvideo, widget: markdown}


